services:
  design-flow:
    build:
      context: .
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    image: design-flow-pro
    container_name: design-flow-pro
    ports:
      - "80:3001"
    restart: always
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
    env_file:
      - .env
    networks:
      - design-network

networks:
  design-network:
    driver: bridge
